[package]
name = "zstd_read_line"
version = "0.2.0"
authors = ["Vee Satayamas <5ssgdxltv@relay.firefox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zstd = "0.9"
memchr = "2"

[lib]
crate-type = ["cdylib"]

